### ISSUE TITLE
[BUG] Serverbooster last version error spam

### ISSUE THREAD

**Issue by OverBrave** [LoneDev6/ServerBooster#1]
**Describe the bug**
I using default configs but this error spam on console: Task #47

**Screenshots**
![image](https://user-images.githubusercontent.com/47111280/80426558-a4668e80-88ee-11ea-8c8e-66f8b7edbb0f.png)

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: optifine 1.15.2 pre-13
 - Plugin version: 1.0.28

**Comment by LoneDev6** [comment]
Thanks for the report and thanks for using github! :D This speeds up development of the plugin

**Comment by LoneDev6** [comment]
Should be fixed in the next update, I will publish in some hours.
If the error appears again please reopen this issue.
Thanks!
