### ISSUE TITLE
Mobstacking does not work

### ISSUE THREAD

**Issue by Lukatjee** [LoneDev6/ServerBooster#3]
Mobs don't stack and when I try to execute the command '/serverbooster mobs forceoptimize'
Error: https://pastebin.com/g6NaPmbW
Server version: Spigot 1.15.2
Plugins: https://pastebin.com/50nRwpTa
ServerBooster Configs:
[ServerBooster.zip](https://github.com/LoneDev6/ServerBooster/files/4649827/ServerBooster.zip)

**Comment by LoneDev6** [comment]
Thanks for the report, I will remove this error
Anyway, you don't need to use /serverbooster mobs forceoptimize, it's for development purposes and should not be executed since the plugin automatically optimizes entities when needed
