### ISSUE TITLE
[BUG] Items disappears

### ISSUE THREAD

**Issue by alejandro0256** [LoneDev6/ServerBooster#5]
**Describe the bug**
If you drop an item just under you and you keep pressing the Q while pickup this item it disappears

**To Reproduce**
1. Drop an item just under you.
2. Don't stop pressing Q.

**Expected behavior**
The items shouldn't disappear

**Screenshots**
https://imgur.com/a/JOHmGtp

**Info (please complete the following information):**
 - Server version: paper 1.15.2 (Build: 309)
 - Client version: minecraft Optifine
 - Plugin version: 1.0.31

**Comment by LoneDev6** [comment]
Thanks! this is fixed in the new update I will publish, reopen this issue if you will still have problems
