### ISSUE TITLE
[BUG] Server crashing on startup

### ISSUE THREAD

**Issue by kwascam** [LoneDev6/ServerBooster#73]
**Describe the bug**
Whenever the server starts, it immediately stops.

**To Reproduce**
1. Install the 3 plugins (booster, protocol, lonelibs)
2. Start the server

**Expected behavior**
the server not instantly crashing

**Screenshots**
https://pastebin.com/D8VSSsDs

**Info (please complete the following information):**
 - Server version: paper 1.18.1
 - Client version: fabric 1.18.1
 - Plugin version: 1.1.4

**Additional context**
Hi! Whenever I install your plugin, whenever my server starts it immediately stops
https://pastebin.com/D8VSSsDs
It does not do this without ServerBooster installed.

All 3 plugins (booster, ProtocolLib, LoneLibs) are all the most recent versions. My paper install is also the most recent version.

A similar problems occurs when I attempt to use ItemAdder, yet LoneLibs appears to enable correctly in both instances.

**Comment by LoneDev6** [comment]
Update paper.
There is no reason to stay on 1.18.1, it's old and has issues.
Update to 1.18.2.
