### ISSUE TITLE
Mobs limiter count issue

### ISSUE THREAD

**Issue by PABLORAGNIzc** [LoneDev6/ServerBooster#78]
![image](https://github.com/PluginBugs/Issues-ServerBooster/assets/84411800/c98fc3b7-bd70-48cd-87d5-e6796bca280c)

**Comment by PABLORAGNIzc** [comment]
How can I delete entities if I exceed the limit of 10 entities in the same chunk?

**Comment by LoneDev6** [comment]
Is this the same chunk?
Use F3+G to show them.
