### ISSUE TITLE
[BUG] Dupe items

### ISSUE THREAD

**Issue by CovenanTHD** [LoneDev6/ServerBooster#80]
**Describe the bug**
Hello, excellent plugin, unfortunately it has dupe failures in version 1.20 in which it infinitely and massively generates certain items.
 I would like to please contact someone to patch it as soon as possible.

**video**
Video: https://youtu.be/ujmDQRwGMVM

**Info (please complete the following information):**
 - Server version: 1.20
 - Client version: spigot
 - Plugin version: Server booster 1.1.5

**Comment by LoneDev6** [comment]
Will be checked, thanks.

**Comment by LoneDev6** [comment]
This bug is related to a plugin which is auto-giving you the contents of the chest on block break.
Please provide me the name of the plugin.
