### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Micky117** [LoneDev6/ServerBooster#81]
BUG:

Hello, I recently bought the Server Booster plugin and I have put it on my server that has the ArcLight API and I get an error when starting, I don't know if it is because of the API that I use or something else, but hopefully you can help me here I leave the error:

That the plugin works well since it is paid

Screenshots

![1](https://github.com/PluginBugs/Issues-ServerBooster/assets/140937491/60a0e9b2-4455-45d1-853e-00b3fb55ce96)
![2](https://github.com/PluginBugs/Issues-ServerBooster/assets/140937491/a0c0fccb-7418-4b79-a1e6-331bb762de3b)
![3](https://github.com/PluginBugs/Issues-ServerBooster/assets/140937491/bbe405e7-fd10-48a5-88ff-67ebb7f83c64)

Info 
 - Server version: 1.19.2
 - Client version: Arc Ligth
 - Plugin version: 1.1.5

**Comment by LoneDev6** [comment]
Update to 1.19.3 or 1.19.4
