### ISSUE TITLE
[BUG] item name is not output normally.

### ISSUE THREAD

**Issue by Kimihakiwi** [LoneDev6/ServerBooster#83]
**Describe the bug**
item name is not output normally.

**Screenshots**
<img width="1162" alt="image" src="https://github.com/PluginBugs/Issues-ServerBooster/assets/114659946/74b431fa-bcc5-479b-a31c-4d472ae408e5">

**Vidio**
https://youtu.be/qip_pdAGDsI

**Info (please complete the following information):**
 - Server version: pufferfish 1.20.1
 - Client version: fabric 1.20.1
 - Plugin version: ServerBooster 1.1.6-r2

**Comment by LoneDev6** [comment]
Thanks, this will be fixed
