### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Rabahwc** [LoneDev6/ServerBooster#96]
Cant use Lonelib protocol and sbooster. Sbooster shuts down and causes server to keep restart. has something to do with the pig_zombie having the wrong configurations.other error disables sbooster saying something about tracking error from lone.dev.And yes I have the most recent version of all 3.Protocol and lonelib can launch on their own perfectly fine but when I try to combine serverbooster. Server doesn’t work. Forge 1.19.2
![image](https://github.com/PluginBugs/Issues-ServerBooster/assets/156968608/770df718-375e-4136-b215-0c480b7fa761)

![IMG_3407](https://github.com/PluginBugs/Issues-ServerBooster/assets/156968608/49be9e9d-1153-4227-a4a0-fc6249315d20)
![image](https://github.com/PluginBugs/Issues-ServerBooster/assets/156968608/fc5004bc-db6b-40c4-8d32-d93922755a67)

**Comment by LoneDev6** [comment]
Please share the complete log file of when this happens.
Anyway update to 1.19.4.
1.19.1 is old and bugged.

Also please do not post screenshots of errors (in this case even a picture...), post the log file next time.
(this is the same thing any other developer would tell you btw).
Thanks.
